// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QtBXusOLzD27wPBqnyaals7S7YJzOeo',
    appId: '1:1084888108318:web:e082f2342ca1728e398d0f',
    messagingSenderId: '1084888108318',
    projectId: 'fit-app-63796',
    authDomain: 'fit-app-63796.firebaseapp.com',
    storageBucket: 'fit-app-63796.firebasestorage.app',
    measurementId: 'G-YMF7Y9LCC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQtGtRpiTcokp_KvTmua2X4FZKWWn1Us',
    appId: '1:1084888108318:android:515f095ff096f393398d0f',
    messagingSenderId: '1084888108318',
    projectId: 'fit-app-63796',
    storageBucket: 'fit-app-63796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb370k8n6f3nF7EdVrpXHBAnh0vwX_OvY',
    appId: '1:1084888108318:ios:b2a9769f95fdba6c398d0f',
    messagingSenderId: '1084888108318',
    projectId: 'fit-app-63796',
    storageBucket: 'fit-app-63796.firebasestorage.app',
    iosClientId: '1084888108318-2da4rsol0aht0nb4neuk8b3mt5hjv6cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb370k8n6f3nF7EdVrpXHBAnh0vwX_OvY',
    appId: '1:1084888108318:ios:b2a9769f95fdba6c398d0f',
    messagingSenderId: '1084888108318',
    projectId: 'fit-app-63796',
    storageBucket: 'fit-app-63796.firebasestorage.app',
    iosClientId: '1084888108318-2da4rsol0aht0nb4neuk8b3mt5hjv6cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QtBXusOLzD27wPBqnyaals7S7YJzOeo',
    appId: '1:1084888108318:web:6736bfea690ca1e8398d0f',
    messagingSenderId: '1084888108318',
    projectId: 'fit-app-63796',
    authDomain: 'fit-app-63796.firebaseapp.com',
    storageBucket: 'fit-app-63796.firebasestorage.app',
    measurementId: 'G-4LRK5WFGFB',
  );
}
